version: '2'
services:
    diamond-app:
        image: diamond
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger,tls
            - SPRING_DATASOURCE_URL=jdbc:mysql://diamond-mysql:3306/diamond?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://diamond-elasticsearch:9200
        ports:
            - 443:8080
    diamond-mysql:
        extends:
            file: mysql.yml
            service: diamond-mysql
    diamond-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: diamond-elasticsearch
